- op: add
  path: /spec/template/spec/volumes/-
  value: {"name":"etc-containers", "hostPath":{"path":"/etc/containers", "type": "Directory"}}
- op: add
  path: /spec/template/spec/containers/1/volumeMounts/-
  value: {"name":"etc-containers", "readOnly": true, "mountPath":"/etc/containers"}
